### ISSUE TITLE
ModuleNotFoundError: No module named 'manage'

### ISSUE THREAD

**Issue by michaeltoohig** [mtnbarreto/flask-base-api#1]
Running `docker-compose up -d` results in `flask-base-service` exiting

```
         Name                       Command                  State                                   Ports
--------------------------------------------------------------------------------------------------------------------------------------
celery-worker            /bin/sh -c celery -A proje ...   Up
flask-base-db            docker-entrypoint.sh postgres    Up (healthy)   0.0.0.0:5435->5432/tcp
flask-base-service       /bin/sh -c gunicorn -b 0.0 ...   Exit 3
message-broker-service   docker-entrypoint.sh rabbi ...   Up             15671/tcp, 0.0.0.0:15675->15672/tcp, 25672/tcp, 4369/tcp,
                                                                         5671/tcp, 0.0.0.0:5675->5672/tcp
nginx                    nginx -g daemon off;             Restarting
redis-db                 docker-entrypoint.sh redis ...   Up             0.0.0.0:6375->6379/tcp
swagger                  sh /usr/share/nginx/docker ...   Up             0.0.0.0:8080->8080/tcp
```

And then the logs show the following.

```
Attaching to flask-base-service
flask-base-service        | [2019-03-20 10:04:57 +0000] [6] [INFO] Starting gunicorn 19.7.1
flask-base-service        | [2019-03-20 10:04:57 +0000] [6] [INFO] Listening at: http://0.0.0.0:5000 (6)
flask-base-service        | [2019-03-20 10:04:57 +0000] [6] [INFO] Using worker: sync
flask-base-service        | [2019-03-20 10:04:57 +0000] [9] [INFO] Booting worker with pid: 9
flask-base-service        | [2019-03-20 10:04:57 +0000] [9] [ERROR] Exception in worker process
flask-base-service        | Traceback (most recent call last):
flask-base-service        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
flask-base-service        |     worker.init_process()
flask-base-service        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
flask-base-service        |     self.load_wsgi()
flask-base-service        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
flask-base-service        |     self.wsgi = self.app.wsgi()
flask-base-service        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
flask-base-service        |     self.callable = self.load()
flask-base-service        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
flask-base-service        |     return self.load_wsgiapp()
flask-base-service        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
flask-base-service        |     return util.import_app(self.app_uri)
flask-base-service        |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
flask-base-service        |     __import__(module)
flask-base-service        | ModuleNotFoundError: No module named 'manage'
flask-base-service        | [2019-03-20 10:04:57 +0000] [9] [INFO] Worker exiting (pid: 9)
flask-base-service        | [2019-03-20 10:04:57 +0000] [6] [INFO] Shutting down: Master
flask-base-service        | [2019-03-20 10:04:57 +0000] [6] [INFO] Reason: Worker failed to boot.
```

I've tried changing the `CMD` and trying to run the `gunicorn` command from inside the docker container itself but no luck. 

I did find the containers `/usr/src/app` directory empty when I was exploring it with bash. I think that is related to the code being shared with the container as a volume on my local machine in the `docker-compose.yml` file. But I'm not very experienced with docker yet and I think I need a little more documentation to get started.

Thank you.

**Comment by cheluskis** [comment]
Hi @michaeltoohig,

I followed the steps again exactly, and it works, on Docker version 18.09.1, build 4c52b90, something similar should be fine.

It seems your gunicorn did not build fine. Or maybe tried many times and have repeated containers or maybe process occupying the same ports.

Could please rebuild doing something like this:

`docker-compose down -v` # stop containers
`docker-compose up -d` # rebuild, optionally add --no-cache
`docker ps` # show docker processes 

and show us the log. Additionally which OS are you using?

Thanks for joining us!,
Best

**Comment by michaeltoohig** [comment]
I built the project on a new Debian installation and its okay now. I previously was running it via Docker for Windows controlled by docker installed in WSL (Debian). 

I will redownload/rebuild the project on my windows machine and verify I didn't introduce the error myself.

**Comment by cheluskis** [comment]
Glad you made it work.
Remember for Windows prior 10 enterprise (I guess), you need to use the tool docker-machine. I made it work on Windows 8.1, using git bash.

Feel free to share your findings,
Regards,

**Comment by michaeltoohig** [comment]
I'll look into that too thank you and let you know what I find.

But while you are here I want to thank you for the project. I come from using Flask-RestPlus and enjoy seeing the patterns in this project since they are novel to me and I can learn from it.
